# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import the dataset

In [2]:
from sklearn.datasets import make_classification

In [3]:
X, y = make_classification(n_samples=1000, n_features=10, n_informative=3, n_classes=3, random_state=42)

In [4]:
X[:5]

array([[ 0.7715326 , -1.47433614,  2.19664605, -0.67899174,  0.76747934,
        -1.22617936, -0.23756628,  0.68174341,  1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, -3.81836772,  0.63596775,
         1.60952067, -0.15313504, -0.47417818,  1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 ,  1.18528138, -0.73677014,
        -1.40681501,  0.68478283, -0.32202815, -1.45103394,  1.32543211],
       [-1.02241959,  1.3817867 ,  2.01527511,  0.86143427,  1.29064446,
        -1.88964929,  1.00913804,  0.36311563, -1.84423789,  0.31110999],
       [-0.13116121, -2.07900845,  1.48374391,  1.63685752, -0.7348109 ,
        -0.64015446,  2.66642175, -1.08574771, -0.89285099,  0.02979617]])

In [5]:
y[:5]

array([1, 2, 1, 1, 2])

# Train test split

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1011)

In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((700, 10), (300, 10), (700,), (300,))

# Create the logistic regression model

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
logistic = LogisticRegression(multi_class='ovr')

In [12]:
logistic.fit(X_train, y_train)

C:\Users\user\anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [13]:
y_pred = logistic.predict(X_test)
y_pred[:10]

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 2])

In [14]:
y_pred_proba = logistic.predict_proba(X_test)
y_pred_proba[:5]

array([[0.23093701, 0.60081929, 0.1682437 ],
       [0.46594034, 0.52245823, 0.01160143],
       [0.59993071, 0.34668107, 0.05338823],
       [0.65632128, 0.19240984, 0.15126888],
       [0.28605047, 0.65555142, 0.05839811]])

# Check the performance of the model

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [17]:
score = accuracy_score(y_test, y_pred)
score

0.64

In [18]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[72, 24,  7],
       [42, 34, 19],
       [ 5, 11, 86]], dtype=int64)

In [19]:
class_report = classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.61      0.70      0.65       103
           1       0.49      0.36      0.41        95
           2       0.77      0.84      0.80       102

    accuracy                           0.64       300
   macro avg       0.62      0.63      0.62       300
weighted avg       0.62      0.64      0.63       300

